database = {
    "artists": ("The Notorious B.I.G.",),
    "albums": ("Life After Death", "1997-03-25", True, False),
    "discs": (1, "Disc Two", 2),
    "songs": (1, "Notorious Thugs", 1, 367,
              "the-notorious-big/life-after-death/disc-two/01_notorious_thugs.flac",
              "Qobuz", 1),
    "artists_albums": (1, 1),
    "artists_songs": (1, 1, False),
    "producers_songs": (1, 1, False, False),
    "playlists": ("Paid In Full",),
    "playlists_songs": (1, 1),
    "hubs": ("Bad Boy Records",),
    "hubs_albums": (1, 1),
}

metadata_form = {
    "album_artists": "The Notorious B.I.G.",
    "album": "Life After Death",
    "track_count": "1",
    "release_date": "1997-03-25",
    "hubs": "Bad Boy Records",
    "multidisc": "True",
    "disc_name": "Disc Two",
    "disc_number": "2",
    "track1_title": "Notorious Thugs",
    "track1_song_artists": "The Notorious B.I.G.; Bone Thugs-N-Harmony",
    "track1_group_members": "Layzie Bone; Krayzie Bone; Bizzy Bone",
    "track1_producers": "Stevie J; Puff Daddy",
    "track1_coproducers": "Easy Mo Bee",
    "track1_additional_producers": "RZA",
    "track1_comment": "Remove intro at ~0:00",
    "track1_source": "Soulseek",
    "track1_path": "01_notorious_thugs.flac",
}
