# Generated by Django 5.0.6 on 2024-08-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disc",
            options={"ordering": ["number"]},
        ),
    ]
