# Generated by Django 5.1.3 on 2024-11-17 02:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=600)),
                ("release_date", models.DateField()),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "album_type",
                    models.CharField(
                        choices=[
                            ("album", "album"),
                            ("multidisc", "multidisc"),
                            ("single", "single"),
                        ],
                        default="album",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["artists__name", "release_date"],
            },
        ),
        migrations.CreateModel(
            name="AlbumArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.artist"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                related_name="album_artists", through="api.AlbumArtist", to="api.artist"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumartist",
            constraint=models.UniqueConstraint(
                fields=("album", "artist"), name="duplicate_album_artist"
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("release_date"),
                name="duplicate_album",
            ),
        ),
    ]
