# Generated by Django 5.0.6 on 2024-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disc',
            constraint=models.CheckConstraint(check=models.Q(('number__gte', 1)), name='disc_number_greater_than_0'),
        ),
    ]
