# Generated by Django 5.0.6 on 2024-06-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disc_disc_number_greater_than_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
