# Generated by Django 5.1.3 on 2024-11-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_album_albumartist_album_artists_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["release_date"]},
        ),
    ]
