# Generated by Django 5.0.6 on 2024-08-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_disc_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(check=models.Q(('single', True), ('multidisc', True), _negated=True), name='singles_can_not_be_multidisc'),
        ),
    ]
