# Generated by Django 5.0.6 on 2024-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_song_path'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(check=models.Q(('track_number__gte', 1)), name='track_number_greater_than_0'),
        ),
    ]
