# Generated by Django 5.0.6 on 2024-08-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='catalog.Feature', to='catalog.artist'),
        ),
    ]
