# Generated by Django 5.0.6 on 2024-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_song_track_number_greater_than_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
