# Generated by Django 5.0.6 on 2024-06-20 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_playlist_options_playlist_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disc'),
        ),
    ]
