# Generated by Django 5.0.6 on 2024-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_feature_producer_must_have_a_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='producers_not_included_in_groups',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='producer_must_have_a_role',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('group', True), ('producer', True), _negated=True), name='producers_not_included_in_groups'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', True), models.Q(('role', ''), _negated=True)), name='producer_must_have_a_role'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', False), models.Q(('role', ''), _negated=True), _negated=True), name='only_producers_have_roles'),
        ),
    ]
