# Generated by Django 5.0.6 on 2024-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='only_producers_have_roles',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', False), ('role', '')), name='only_producers_have_roles'),
        ),
    ]
