# Generated by Django 5.0.6 on 2024-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_feature_only_producers_have_roles_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='unique_vocalist',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='unique_producer',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='producer_must_have_a_role',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='only_producers_have_roles',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('artist', 'song', 'producer'), name='unique_credit'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', True), models.Q(('role__exact', ''), _negated=True)), name='producer_must_have_a_role'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', False), ('role__exact', '')), name='only_producers_have_roles'),
        ),
    ]
