# Generated by Django 5.0.6 on 2024-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_feature_unique_vocalist_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='producers_not_included_in_groups',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='producer_must_have_a_role',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='only_producers_have_roles',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('group__exact', True), ('producer', True), _negated=True), name='producers_not_included_in_groups'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer__exact', True), models.Q(('role__exact', ''), _negated=True)), name='producer_must_have_a_role'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer__exact', False), ('role__exact', '')), name='only_producers_have_roles'),
        ),
    ]
