# Generated by Django 5.0.6 on 2024-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_song_track_number_greater_than_0'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songproducer',
            constraint=models.CheckConstraint(check=models.Q(('role', ''), _negated=True), name='role_required'),
        ),
    ]
