# Generated by Django 5.0.6 on 2024-08-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-play_count', '-album__release_date', 'disc__number', 'track_number']},
        ),
    ]
