# Generated by Django 5.0.6 on 2024-08-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_song_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='artists', through='catalog.Feature', to='catalog.artist'),
        ),
    ]
