# Generated by Django 5.0.6 on 2024-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_song_artists'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group', False), ('producer', False)), models.Q(('group', True), ('producer', False)), models.Q(('group', False), ('producer', True)), _connector='OR'), name='producers_not_included_in_groups'),
        ),
    ]
