# Generated by Django 5.0.6 on 2024-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_feature_producers_not_included_in_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', True), ('role', '')), name='producer_must_have_a_role'),
        ),
    ]
