# Generated by Django 5.0.6 on 2024-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_feature_producers_not_included_in_groups_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='producers_not_included_in_groups',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='producer_must_have_a_role',
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='only_producers_have_roles',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group', False), ('producer', False)), models.Q(('group', True), ('producer', False)), models.Q(('group', False), ('producer', True)), _connector='OR'), name='producers_not_included_in_groups'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('producer', False), ('role__exact', '')), name='only_producers_have_roles'),
        ),
    ]
