# Generated by Django 5.0.6 on 2024-08-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_feature_producers_not_included_in_groups_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='only_producers_have_roles',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('producer', False), ('role__exact', '')), models.Q(('producer', True), models.Q(('role__exact', ''), _negated=True)), _connector='OR'), name='only_producers_have_roles'),
        ),
    ]
