# Generated by Django 5.0.6 on 2024-08-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_feature_only_producers_have_roles_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='producers_not_included_in_groups',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.CheckConstraint(check=models.Q(('group', True), ('producer', True), _negated=True), name='producers_not_included_in_groups'),
        ),
    ]
