# Generated by Django 5.0.6 on 2024-08-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_feature_producers_not_included_in_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SongProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='song',
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-play_count', '-album__release_date', 'disc', 'track_number']},
        ),
        migrations.RemoveConstraint(
            model_name='song',
            name='track_number_greater_than_0',
        ),
        migrations.AlterField(
            model_name='song',
            name='disc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='songartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='songartist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='artists', through='catalog.SongArtist', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='songproducer',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='songproducer',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='producers',
            field=models.ManyToManyField(related_name='producers', through='catalog.SongProducer', to='catalog.artist'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(check=models.Q(('disc__gte', 1), ('disc__isnull', True), _connector='OR'), name='disc_number_greater_than_0_or_null'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddConstraint(
            model_name='songartist',
            constraint=models.UniqueConstraint(fields=('song', 'artist'), name='unique_vocalist'),
        ),
        migrations.AddConstraint(
            model_name='songproducer',
            constraint=models.UniqueConstraint(fields=('song', 'producer'), name='unique_producer'),
        ),
    ]
