# Generated by Django 5.0.6 on 2024-08-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_songartist_songproducer_remove_feature_artist_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(check=models.Q(('track_number__gte', 1)), name='track_number_greater_than_0'),
        ),
    ]
