# Generated by Django 5.0.6 on 2024-08-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_songproducer_role_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songproducer',
            name='role_required',
        ),
    ]
